Retry with friendly error message on HTTP 5xx server.
Software-Improvement-Group/sigridci pull request #16
Opened 2021-04-15 15:36 UTC by dennis-sig

2021-04-15 15:46 UTC, tukraus requested changes

2021-04-15 15:46 UTC, tukraus commented on sigridci/sigridci.py
> +            log("HTTP status {e.code} when connecting to Sigrid, retrying")
I think this should be an f-string ?

2021-04-15 15:46 UTC, tukraus commented on test/sigridcitest.py
> +        apiClient.processHttpError(urllib.error.HTTPError("http://www.sig.eu", 502, "", {}, None))
Maybe split this in 2 tests where one expects the Exception (client error) and the other (server error) does not?

2021-04-15 16:14 UTC, janlaan commented
This fixes the issue when the error occurs during `fetchAnalysisResults`. It does not address the scenario where the HTTP call in`submitUpload` fails with a 4xx or 5xx HTTP error.

2021-04-16 10:02 UTC, dennis-sig commented
@tukraus @janlaan Could you have another look? Error message in the various situations should be more aligned now.

2021-04-16 13:01 UTC, janlaan commented
> @tukraus @janlaan Could you have another look? Error message in the various situations should be more aligned now.

LGTM

2021-04-20 13:54 UTC, tukraus approved these changes

2021-04-20 14:01 UTC, merged