Document new AQ option.
Software-Improvement-Group/sigridci pull request #306
Opened 2023-09-20 10:07 UTC by dennis-sig

2023-09-20 11:34 UTC, jimivdw requested changes
Just one small typo to fix.

2023-09-20 11:34 UTC, jimivdw commented on docs/capabilities/architecture-quality.md
> +You can define *groups* and *annotations* in [your configuration](../reference/analysis-scope-configuration.md#architecture-quality). This information will then be depicted as an overlap on top of th
```suggestion
You can define *groups* and *annotations* in [your configuration](../reference/analysis-scope-configuration.md#architecture-quality). This information will then be depicted as an overlay on top of the architecture visualization in Sigrid.
```

2023-09-21 07:31 UTC, jimivdw approved these changes

2023-09-21 07:32 UTC, jimivdw approved these changes
Approved ✅

2023-09-21 07:49 UTC, tukraus approved these changes

2023-09-21 08:21 UTC, merged