Add Guidelines for using Objectives
Software-Improvement-Group/sigridci pull request #411
Opened 2024-03-26 15:09 UTC by dessens0

2024-04-22 07:30 UTC, dennis-sig commented
@dessens0 Don't forget to add the new page to the menu, which is literally `menu.html`. There is a new section for this kind of content, also including @lbergmans's new page.

2024-04-25 08:59 UTC, dennis-sig requested changes
For starters: this is great!

- I really like the "Objectives and team autonomy" section.
- The "Using Software Quality Objectives: Jobs to be Done" section is too abrupt for me. I would create a section that bridges the vision that came before with the more step-by-step introduction that come after. 
- Some of the headers randomly capitalize words. I think our style guide says it should be "This is a title" and not "This is a Title" or "This Is A Title".
- The "engineering leaders" is what we call the architect persona elsewhere in the documentation. What we could do to avoid confusion, is just call it "engineering leaders (e.g. architects, lead developers, etc.)".
- The table in "Link Goals to Objectives" is nice, but I've also seen it create a lot of confusion. We need to be explicit that Sigrid does not directly measure those things, this is more of a structure to communicate why certain (technical) things are important. We also have a rather obscure definition of scalability that includes *functional* scalability. I've seen many people get confused over that, so we might want to add one-sentence explanations of what we mean by those benefits.
- Oh, and I think the new page definitely deserves a link in the top-level menu in `menu.html`

2024-04-30 07:26 UTC, lbergmans approved these changes

2024-04-30 09:54 UTC, dessens0 commented on docs/workflows/best-practices-objectives.md
- While there might be a bit of chicken-and-egg with governance and objectives, I'd think you'd have to get together a group of people first to have the discussion on objectives. To me that implies that you need to do governance first. But at the same time, there might be a bit of back and forth, so you might have a group of people and when you start discussing, you decide you need someone else to be involved as well.
- Same goes for metadata, you might (as you remark) decide on an objective only to find that you need to exempt certain systems, for which you need to configure metadata.
- I think I'll just mention the concept of iteration in general with some examples.

2024-04-30 10:56 UTC, dessens0 commented on docs/workflows/best-practices-objectives.md
- I'm using the term 'organization' as a more neutral replacement for 'business' since not all customer organizations are businesses.

2024-05-01 14:45 UTC, dessens0 commented on docs/workflows/best-practices-objectives.md
I converted the table to a markdown table.

2024-05-01 15:02 UTC, dessens0 commented on docs/workflows/best-practices-objectives.md
I'd like to leave the `Review Objectives and Governance` section in there for now, it would also make for a nicer flow chart.

2024-05-01 15:04 UTC, dessens0 commented on docs/workflows/best-practices-objectives.md
Other than that, I think I addressed most comments.

2024-05-02 15:09 UTC, lbergmans commented on docs/workflows/best-practices-objectives.md
> * I'm using the term 'organization' as a more neutral replacement for 'business' since not all customer organizations are businesses.

My remark about business vs organization was about the text below the table: in the table and text above, you talk about 'organizational concerns', and in the paragraph below it, you talk about 'business concerns' --> that seems inconsistent (or is there a reason for this?)


> I'm not sure about the links you provide, at least they don't work.

I just copied links (from the preview) or created dummy links that still need to be defined,  the idea being that when you refer to a section in the documentation, you can use a hyperlink.

> And I now noticed:

"For each technical concern, separate best practice document within the Sigrid documentation provides our recommended (set of) objective(s). " --> add "a" to "separate best practice document"..

2024-05-08 07:25 UTC, dennis-sig approved these changes

2024-05-08 07:25 UTC, dennis-sig commented
@dessens0 No more comments from my side. Do you want to still address Lodewijk's last comment, or are we good to go?

2024-05-08 08:05 UTC, dessens0 commented
@dennis-sig I addressed @lbergmans 's comments. Not sure I covered all the link-related stuff but we can always add more links as we go. So I'd say we're good to go.

2024-05-08 08:22 UTC, merged