UM update for Maintainer role
Software-Improvement-Group/sigridci pull request #444
Opened 2024-05-20 17:50 UTC by olimoli9160

2024-05-27 10:34 UTC, dennis-sig approved these changes

2024-05-27 10:35 UTC, dennis-sig commented
Approved from a pure documentation point of view. The review by Jimi and/or Valerio should clarify whether the documentation correctly describes how it actually works though.

2024-05-29 07:13 UTC, jimivdw requested changes

2024-05-29 07:13 UTC, jimivdw commented on docs/organization-integration/usermanagement.md
> +✔✔ **Global Scope**: User is able to perform this action across any system in the portfolio
For the sake of readability in dark mode, I propose to replace the ✔s with ✅s. Also split up the Edit Authorization Groups in its 3 sub-parts.

```suggestion
| **Portfolio Overview**
| View Dashboard | ✅ | ✅ | ✅✅ |
| View Systems | ✅ | ✅ | ✅✅ |
| **Capability Specific Overviews**
| View Dashboards | ✅ | ✅ | ✅✅ |
| View Ratings | ✅ | ✅ | ✅✅ |
| Favorite Systems | ✅ | ✅ | ✅✅ |
| **Findings and Refactoring Candidates**
| View Findings | ✅ | ✅ | ✅✅ |
| Edit Findings | ✅ | ✅ | ✅✅ |
| View Finding Audit Trails | ✅ | ✅ | ✅✅ |
| Create Manual Findings | | ✅ | ✅✅ |
| **Source Code**
| View Source Code | ✅ | ✅ | ✅✅ |
| **Meta-data**
| View metadata | ✅ | ✅ | ✅✅ |
| Configure metadata | | ✅ | ✅✅ |
| **Objectives**
| View objectives | ✅ | ✅ | ✅✅ |
| Configure system-level objectives | | ✅ | ✅✅ |
| Configure portfolio-level objectives | | | ✅✅ |
| **User Management**
| View Users | ✅ | ✅ | ✅✅ |
| Create / Delete Users | | | ✅✅ |
| Edit User Permissions | | ✅ | ✅✅ |
| Edit User Details (other than self) | | | ✅✅ |
| View User Status Details | | | ✅✅ |
| Edit User Role | | | ✅✅ |
| Reset User Password / MFA | | | ✅✅ |
| Create / Delete Authorization Groups | | | ✅✅ |
| Edit Authorization Group Permissions | | ✅ | ✅✅ |
| Edit Authorization Group Members | | ✅(1) | ✅✅ |
| Edit Authorization Group Details | | ✅(1) | ✅✅ |

✅ **Limited Scope:** User is only able to perform this action on systems that are explicitly accessible to the user  
✅✅ **Global Scope**: User is able to perform this action across any system in the portfolio  
(1) Only for Groups the Maintainer is a member of
```

2024-05-30 06:02 UTC, jimivdw approved these changes
LGTM 👍

2024-05-30 07:25 UTC, merged