Extend scope file schema for more advanced dependencychecker.exclude …
Software-Improvement-Group/sigridci pull request #482
Opened 2024-07-29 12:21 UTC by dennis-sig

…options.

2024-07-29 12:28 UTC, patveck approved these changes

2024-07-29 12:32 UTC, dennis-sig commented
@fabianl-sig Could you also double-check? Without the schema change you can't actually create any scope file with the new option, because they will not pass the validation.

2024-07-29 13:00 UTC, fabianl-sig requested changes

2024-07-29 13:00 UTC, fabianl-sig commented on resources/sigrid-scope-file.schema.json
> +          "description": "List of paths and/or dependencies that should be ignored for Open Source Health."
Do we also want to update this description to include the new options and/or do we want to also add descriptions to each type?

Leaving this until it's fully rolled out is also fine by me.

2024-07-29 13:00 UTC, fabianl-sig commented on test/test_scope_file_schema.py
> +            self.assertTrue("{'something': 'noot'} is not valid under any of the given schemas" in e.message)
If `jsonschema.ValidationError` is not thrown here the test would still pass since nothing would actually be asserted. Something like:
```suggestion
        try:
            parsedScope = yaml.load(scope, Loader=yaml.FullLoader)
            jsonschema.validate(instance=parsedScope, schema=self.schema)
            self.assertTrue(False, "ValidationError should have been raised")
        except jsonschema.ValidationError as e:
            self.assertTrue("{'something': 'noot'} is not valid under any of the given schemas" in e.message)
```
should do the trick.

2024-07-30 13:32 UTC, fabianl-sig approved these changes

2024-07-31 07:00 UTC, merged